apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: backend  # Replace with correct label of your backend pods
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

